### ISSUE TITLE
xunit-viewer is very slow to load these results

### ISSUE THREAD

**Issue by smoofra** [lukejpreston/xunit-viewer#106]
See attached xml input here: [results.xml.txt](https://github.com/lukejpreston/xunit-viewer/files/7139579/results.xml.txt)

xunit-viewer is very slow to load on this input -- and that's abridged.   If I try it on the whole python regression suite output it pretty much never finishes loading.

It seems to be spending a ton of time in fortawesome processing DOM mutation callbacks from react, or something.

* xunit-viewer version 7.1.5
* node version 15.6.0
* I tested in Safari and Chrome, same result.

**Comment by phe-sto** [comment]
The same happen on my tests, their finish loading with Firefox and Chrome.

**Comment by lukejpreston** [comment]
Is it slow in the command line or when loading the page? Or both?

**Comment by lukejpreston** [comment]
I have added two things for this, and it would be interesting if you could test it and let me know what you think. I hope these changes make your experience with this library better (I used your file, and it seemed loads better for me)

`7.1.8` now has a loading spinner while parsing the files and only renders the suites and tests when they are visible.

I haven't looked at the parsing logic as it seemed to be fast for me. I think the issue was rendering.

If you think this is better then please let me know and we can close this issue.

**Comment by smoofra** [comment]
> Is it slow in the command line or when loading the page? Or both?

slow in the browser

**Comment by lukejpreston** [comment]
@smoofra thanks for the reply. When you get the chance could you test against the latest version and let me know if it is still too slow please?

When I load the data set you provided in Safari, Chrome and Firefox it loads pretty much instantly for me now. I'd be curious to see what your experience is like now.

**Comment by smoofra** [comment]
I tried it with 7.1.9 on the same data.    It works instantly now.    Massively faster than before!

**Comment by lukejpreston** [comment]
@smoofra for checking, glad the change worked for you 😄
