### ISSUE TITLE
v7 user experience stuttering

### ISSUE THREAD

**Issue by ldziadkowiec** [lukejpreston/xunit-viewer#138]
We were being using xunit-viewer for a long time for great success. The v5 gave uz report experience we loved. The most common usage was to quickly filter-out passing test-suites and leave only those who failed. We were forced to upgrade to v7 due to problems with old dependencies with vulnerabilities and we are not able to use v7 as we were used to. Out suite consists of like 200 test suites while each suite has about 5-20 tests. Our tests has also properties with urls to videos etc... for direct review of the failed reason if it is an UI based fail.
So, if any test fails within test-suite, there is no way to filter it directly and quickly. We have to set Visible to "OFF" for all "Passed" Tests. Then turn "All" Properties to "OFF". This setup makes empty test-suites to be hidden and only those which have failed tests are shown.
Then we have to write down each failing test-suite, turn back Visibility for "All" Passed tests ON and turn Properties ON.
Then filter out each failing tests manually by one and go through the tests until hitting the one which fails.

I was able to withstand this horribe steps like 5 times and now I'm going through console log only, since it is 10 times faster than toggling all the insane logic to see my failing tests.
The v5 UI was excellent, two clicks to hide all failing suited and that's it. We are no longer using unit-viewer as it became very user unfriendly. Is there any hope to give back better experience ? If no, we would look for some substitute beside false hopes.

**Comment by lukejpreston** [comment]
Hi @ldziadkowiec, sorry you haven't had the best experience with Xunit Viewer.

I will admit it has been a while since I've worked on Xunit Viewer. It is a quiet project chugging along with plenty of downloads.

What you say makes sense to me. I was thinking of adding a quick `unhealthy/healthy/all` dropdown to hide `passing/skipped` tests and show `error/failure/unknown`, but I never got around to it.

I will dedicate some time to getting this for you since you are so enthusiastic about this project 🙌 

But I can't promise it will be a fast turnaround as I have other commitments. This is an open-source project, so if you or anyone wants to create a PR

This is the design I was thinking of is a dropdown on the right. It ties in with a print view button I want to add to toggle between fast mode and print mode. This is the sketch in my head for it what I would like to add. Would something like this help?

![xunit-viewer-idea](https://github.com/lukejpreston/xunit-viewer/assets/4129128/8ae87ce7-c32c-4215-9c70-26f7855f5fca)

The last part I have never had time for is adding routing to Xunit Viewer to allow people to save shortcuts in the URL to make things like this even quicker.

**Comment by lukejpreston** [comment]
I think I understood what you wanted and now have a v9 to address it 😄

<img width="1383" alt="image" src="https://github.com/lukejpreston/xunit-viewer/assets/4129128/5cce32fb-4a64-458b-b861-cb7abe2223f1">

There is now a dropdown for fast filtering to get the errors only, which is also the default. You can still filter like usual but now a dropdown for some common filtering of tests.

I would be interested in what you think about this feature @ldziadkowiec
