### ISSUE TITLE
HTML characters are not escaped

### ISSUE THREAD

**Issue by callumlocke** [lukejpreston/xunit-viewer#17]
If you have any HTML syntax in your error strings, it completely breaks the report page.

**Comment by lukejpreston** [comment]
Can you give an example please? Sounds like invalid xml

**Comment by barrettkingram** [comment]
I'll chime in because I've also had issues with this. If you have XML like the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="my_test_suite" tests="7" time="33.034525957" failures="4" errors="0" skipped="0" assertions="38" timestamp="2018-03-27T22:48:54-05:00">
  <testcase name="my_test_case" time="7.865718009" assertions="6">
    <failure type="Test::Unit::AssertionFailedError" message="&lt;true&gt; expected but was...">
&lt;true&gt; expected but was &lt;false&gt;
  </testcase>
</testsuite>
```
The `&lt;` and `&gt;` are converted to '<' and '>' during parsing so when the message is displayed on the page the browser things they belong to html tags. If you have something like `&lt;/script&gt;` in your error message the page completely breaks because the browser thinks it is a closing script tag.

**Comment by lukejpreston** [comment]
update to v 5.1.0 now there is a toggle raw button on each test

I am changing the UI quite a bit and making the code much more efficient, in the meantime I have come to this solution instead of doing it on everything
