### ISSUE TITLE
Xunit doesnt produce HTML output

### ISSUE THREAD

**Issue by senthil-nathan** [lukejpreston/xunit-viewer#4]
Hi,

I am trying to use the node option.  

I have pulled down the library using 
npm i -D xunit-viewer

my node script  looks as below
const XunitViewerCli = require('xunit-viewer/cli')

XunitViewerCli({
    results: '/Users/xxx/yyy/frisby/tests/results.xml',
    ignore: [],
    output: false,
    title: 'XunitResults',
    port: false,
    watch: false,
    color: true,
    filter: {}
})

I am on the folder where my node script exists and running the following command 

node xunit.js  

no errors and no HTML output    **NOTE : *** nothing happens *****

Trying to debug, I added console logs, I can see it goes cli/index.js and prints options as

{ results: '/Users/xxx/yyy/frisby/tests/results.xml',
  ignore: [ '!*.xml' ],
  output: false,
  terminal: false,
  title: 'Xunit Results',
  port: false,
  watch: false,
  filter: 
   { suites: { value: 'Suite names matching this value', type: [Object] },
     tests: { value: 'Test names matching this value', type: [Object] },
     properties: 
      { value: 'Properties matching with key or value matching this value',
        type: [Object] },
     search: { suites: '', tests: '', properties: '' },
     hideen: { suites: [], tests: [], properties: [] } },
  dev: false }

then goes to cli/start-output.js but never goes in to save or module.exports. 

Any help is appreciated.

**Comment by lukejpreston** [comment]
you said `output: false` you want this to be a value e.g.

```js
XunitViewerCli({
results: '/Users/xxx/yyy/frisby/tests/results.xml',
ignore: [],
output: '/Users/xxx/yyy/frisby/tests/output.html',
title: 'XunitResults',
port: false,
watch: false,
color: true,
filter: {}
})
```

you can omit the file name but you need to specify the folder you wish to save e.g. 

```js
XunitViewerCli({
results: '/Users/xxx/yyy/frisby/tests/results.xml',
ignore: [],
output: '/Users/xxx/yyy/frisby/tests',
title: 'XunitResults',
port: false,
watch: false,
color: true,
filter: {}
})
```

then it will create the file `/Users/xxx/yyy/frisby/testsxunit-viewer.html` also the other values are optional so you can shrink that down to

```js
XunitViewerCli({
results: '/Users/xxx/yyy/frisby/tests/results.xml',
output: '/Users/xxx/yyy/frisby/tests/results.xml',
})
```

if you wanted to run this with an npm script instead of wrapping it in a file you can with

```json
{
  "script": {
     "xunit-viewer": "xunit-viewer --results=/Users/xxx/yyy/frisby/tests/results.xml --output=/Users/xxx/yyy/frisby/tests/output.html"
  }
}
```

or if you are running the script from the `frisby` folder for example

```json
{
  "script": {
     "xunit-viewer": "xunit-viewer --results=frisby/tests/results.xml --output=frisby/tests/output.html"
  }
}
```

or even shorter

```json
{
  "script": {
     "xunit-viewer": "xunit-viewer --results=frisby/tests --output=frisby"
  }
}
```

where it will look for all `xml` files in the folder `frisby/tests` and create the output in the `frisby` folder which would act as your documentation perhaps (that is how I use it)

try some/all of those, hope it helps

**Comment by senthil-nathan** [comment]
awesome, thanks @lukejpreston. It works great !
