### ISSUE TITLE
Error test cases are not handled properly

### ISSUE THREAD

**Issue by nicopaez** [lukejpreston/xunit-viewer#78]
Test cases with Error status are rendered as passed and they are also omitted in the header summary.
Please find an example attached

[Archive.zip](https://github.com/lukejpreston/xunit-viewer/files/4375209/Archive.zip)

**Comment by nicopaez** [comment]
I think I found cause: there are 2 test cases with the same "name" attribute but with different "classname". I think this is a valid situation that should be supported by the tool.

**Comment by lukejpreston** [comment]
Thanks for finding this. I hadn't come across this before, Xunit Viewer parser ignores `classname`. Mainly because the classname and the suite name were the same in all the examples I have. For a quick temporary fix, to get you past this whilst I work a solution, change the name of the tests to be unique

Note to future self for fixing this (please ignore if it makes no sense)

The parsing logic sees the second test with the same name and then concatenates the two tests together since the first test has a `passed` status the second test does not override this status with `error`. The test should use classname, if present, in order to make unique tests as well as the test name itself

Perhaps the view should include classname as well, I have a feeling it was removed because it was useless information but this scenario clearly shows the flaw in that logic

**Comment by nicopaez** [comment]
Thanks for you answer.

I think the classname should be included  in the name of the test because when working in not so small projects it maybe not so obvious in which class the issue is. Maybe the visualization of the classname could be toggle so each one can decide to see it or not.

I am not a Javascript programmer, but if you point me in the right direction I could try to send a merge-request for this.

**Comment by lukejpreston** [comment]
when npm is back up I have something which I resolve this update to `6.2.5` to test it
