### ISSUE TITLE
Testcases order is not kept

### ISSUE THREAD

**Issue by jerome-pouiller** [lukejpreston/xunit-viewer#86]
The order of the Testcases in the output of `xunit-viewer` is not the same than in the original xml file. Moreover, it seems there is no way to predict the order of Testcases in the output.

**Comment by lukejpreston** [comment]
Very good point, the parser should be sorting. As a note to whoever does the work, sort by suitename then by testname or by testname if there are no suites

**Comment by lukejpreston** [comment]
The tests and suites are now sorted in `v7.0.0`

**Comment by sebastianludwig** [comment]
Hey @lukejpreston, thanks for fixing this so quickly. However I'm not sure that the original report has been addressed. If I understand @jerome-pouiller correctly, he wanted the parser to _not_ perform any sorting at all, but instead keep the order of testcases as they are written in the XML. And I'm with him 😅 

For example

```xml
<testsuite tests="3">
    <testcase classname="foo1" name="ASuccessfulTest"/>
    <testcase classname="foo2" name="AnotherSuccessfulTest"/>
    <testcase classname="foo3" name="AFailingTest">
        <failure type="NotEnoughFoo"> details about failure </failure>
    </testcase>
</testsuite>
```

results in

<img width="984" alt="Screenshot 2023-03-17 at 08 52 44" src="https://user-images.githubusercontent.com/1715010/225845048-847a4fae-f2e8-459a-8c2d-c0f412f0e1cf.png">

Notice how the failing test is at the top instead of at the bottom. Would it be possible to add a flag to keep the original order?
