### ISSUE TITLE
Server should listen on localhost

### ISSUE THREAD

**Issue by AgDude** [lukejpreston/xunit-viewer#89]
Currently the "server" option inspects the host ip address. It is typical for development tools to listen on localhost. This is a feature request to provide an option to listen on localhost or to specify the address on which to listen instead of inspecting to the network interfaces.

**Comment by lukejpreston** [comment]
It should be listening to the localhost

The message logged is just a message it doesn't do anything with that value https://github.com/lukejpreston/xunit-viewer/blob/master/src/cli/server.js#L30

Unless you are referring to something else?

**Comment by AgDude** [comment]
When I point the browser at http://127.0.0.1:3000/ I get the message "This site can’t be reached". When I use the link from the console I am able to load the page.  I am using WSL on windows, but other development tools (karma, various dev server) work as expected with this setup.

The command I am using is ` yarn xunit-viewer -r my-project/test-reports -o my-project/test-reports/junit.html -s -w`

**Comment by lukejpreston** [comment]
That library for the console log is here <https://www.npmjs.com/package/ip> and the server uses koa and socket.io.

The reason for using the IP library is because not everyone has access to the machine's localhost; if you consider running it form a docker container or virtual machine and the user has not mapped up to the machine host then `localhost` wouldn't work

I found this which leads me to think it isn't Xunit Viewer at fault <https://github.com/microsoft/WSL/discussions/2471> there is also <https://github.com/microsoft/WSL/issues/4353> where people are still experiencing a recent bug with WSL

I am not really sure how to help sorry, I don't have a windows machine. If you want to spend the time debugging, could you create a hello world koa app and run it using WSL and see if it has the same issue?

How do you run karma and other dev tools, then I can see what libraries they use and if there is a solution to this problem. From my experience, I have run karma from VSCode only and I don't know how VSCode interacts with WSL.

**Comment by AgDude** [comment]
I haven't read all of the details on the WSL issues, but combined with this https://github.com/microsoft/WSL/issues/4769, I agree, this i most likely a WSL issue and not a xunit-viewer issue. I am closing this now.  Thanks for the explanation and for looking into it.
